project_id = "dlxyrjuxylyftwplbdue"

[functions.manage-users-v2]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.bulk-complete-migrations]
verify_jwt = false

[functions.bulk-update-task-status]
verify_jwt = false

[functions.cleanup-devcat-phases]
verify_jwt = false

[functions.fix-specific-migrations]
verify_jwt = false

[functions.regenerate-tasks-by-date]
verify_jwt = false

[functions.remap-migration-templates]
verify_jwt = false