// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlxyrjuxylyftwplbdue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseHlyanV4eWx5ZnR3cGxiZHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NjgwOTcsImV4cCI6MjA4ODU0NDA5N30.1Gaha2dRCUBQUm62C9yWPteUVxkUwoYi6IsJfDx4_Dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});